# -*- coding: utf-8 -*-
"""SmartBin2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYTTd9cDZ7HZEaTgRP6mrpIFzSjXG7p5
"""

!pip install kagglehub torch torchvision scikit-learn tqdm

"""Step 1 — Load Dataset from Kaggle and Build Hierarchical Split"""

import kagglehub
import os
import shutil
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# -------------------------
# DOWNLOAD DATASET
# -------------------------

dataset_path = kagglehub.dataset_download(
    "phenomsg/waste-classification"
)

print("Dataset downloaded to:")
print(dataset_path)

# -------------------------
# CREATE OUTPUT FOLDERS
# -------------------------

OUTPUT_DIR = "waste_split"

TRAIN_DIR = os.path.join(OUTPUT_DIR, "train")
VAL_DIR = os.path.join(OUTPUT_DIR, "val")
TEST_DIR = os.path.join(OUTPUT_DIR, "test")

for d in [TRAIN_DIR, VAL_DIR, TEST_DIR]:
    os.makedirs(d, exist_ok=True)

# -------------------------
# COLLECT IMAGES
# -------------------------

data = {}

for parent in os.listdir(dataset_path):

    parent_path = os.path.join(dataset_path, parent)

    if not os.path.isdir(parent_path):
        continue

    nested_folders = os.listdir(parent_path)

    for nested in nested_folders:

        nested_path = os.path.join(
            parent_path,
            nested
        )

        if not os.path.isdir(nested_path):
            continue

        for child in os.listdir(nested_path):

            child_path = os.path.join(
                nested_path,
                child
            )

            if not os.path.isdir(child_path):
                continue

            label = f"{parent}_{child}"

            images = []

            for img in os.listdir(child_path):

                if img.lower().endswith(
                    (".jpg", ".jpeg", ".png")
                ):
                    images.append(
                        os.path.join(
                            child_path,
                            img
                        )
                    )

            if len(images) > 0:
                data[label] = images

print("\nClasses detected:", len(data))

def split_dataset():

    for label, images in data.items():

        print("\nProcessing:", label)

        train, temp = train_test_split(
            images,
            test_size=0.3,
            random_state=42
        )

        val, test = train_test_split(
            temp,
            test_size=0.5,
            random_state=42
        )

        splits = {
            TRAIN_DIR: train,
            VAL_DIR: val,
            TEST_DIR: test
        }

        for split_dir, files in splits.items():

            class_dir = os.path.join(
                split_dir,
                label
            )

            os.makedirs(
                class_dir,
                exist_ok=True
            )

            for f in tqdm(files):

                shutil.copy(
                    f,
                    class_dir
                )

    print("\nDataset split completed")


split_dataset()

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

val_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

train_dataset = datasets.ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform
)

test_dataset = datasets.ImageFolder(
    TEST_DIR,
    transform=val_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32
)

NUM_CLASSES = len(train_dataset.classes)

print("Number of classes:", NUM_CLASSES)
print(train_dataset.classes)

import torch.nn as nn
from torchvision.models import mobilenet_v2
from torchvision.models import MobileNet_V2_Weights

model = mobilenet_v2(
    weights=MobileNet_V2_Weights.DEFAULT
)

model.classifier[1] = nn.Linear(
    model.last_channel,
    NUM_CLASSES
)

# IMPORTANT: do NOT freeze backbone

for param in model.parameters():
    param.requires_grad = True

model.to(DEVICE)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0001
)

print("Model ready")

EPOCHS = 20

for epoch in range(EPOCHS):

    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        outputs = model(images)

        loss = criterion(
            outputs,
            labels
        )

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(
        f"Epoch {epoch+1}",
        "Loss:",
        running_loss
    )

torch.save(
    model.state_dict(),
    "mobilenetv2_waste_classifier.pt"
)

print("Model saved successfully")

def evaluate_model(model, loader):

    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            outputs = model(images)

            _, predicted = torch.max(
                outputs,
                1
            )

            total += labels.size(0)

            correct += (
                predicted == labels
            ).sum().item()

    accuracy = 100 * correct / total

    return accuracy


test_accuracy = evaluate_model(
    model,
    test_loader
)

print(
    "MobileVNet_V2 Test Accuracy:",
    f"{test_accuracy:.2f}%"
)

# model_loader.py
import torch
import torchvision.models as models

def load_model(pt_path, num_classes, device='cpu'):
    model = models.mobilenet_v2(pretrained=False)
    # Replace classifier head to match your num_classes
    model.classifier[1] = torch.nn.Linear(model.last_channel, num_classes)
    model.load_state_dict(torch.load(pt_path, map_location=device))
    model.eval()
    return model

print(len(train_dataset.classes))

# Should print exactly the 18 class list above in alphabetical order